"""add buyer and seller to order items

Revision ID: 547770885f75
Revises: a1b2c3d4e5f6
Create Date: 2026-08-30 09:34:10.978535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547770885f75'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM order_timeline; DELETE FROM order_items; DELETE FROM orders;')
    op.add_column('order_items', sa.Column('buyer_id', sa.UUID(), nullable=False))
    op.add_column('order_items', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_order_items_buyer_id'), 'order_items', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_order_items_seller_id'), 'order_items', ['seller_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'artisan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'artisan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_seller_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_buyer_id'), table_name='order_items')
    op.drop_column('order_items', 'seller_id')
    op.drop_column('order_items', 'buyer_id')
    # ### end Alembic commands ###
