"""Add push token and update notification enum

Revision ID: 5d03753c8fae
Revises: 686a2b833b87
Create Date: 2026-09-02 15:18:33.570167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d03753c8fae'
down_revision: Union[str, None] = '686a2b833b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tokens_token'), 'push_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Add new NotificationType enum values manually
    new_types = [
        "order_placed",
        "payment_confirmed",
        "order_accepted",
        "order_shipped",
        "order_delivered",
        "order_cancelled",
        "order_refund",
        "payment_received",
        "out_of_stock",
        "product_published",
        "profile_updated",
        "security_alert"
    ]
    for ntype in new_types:
        op.execute(f"ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS '{ntype}'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_token'), table_name='push_tokens')
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
