"""Add structured dimensions to Product

Revision ID: 686a2b833b87
Revises: 547770885f75
Create Date: 2026-09-01 13:51:57.874563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686a2b833b87'
down_revision: Union[str, None] = '547770885f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artisan_profiles', 'business_type')
    op.drop_column('artisan_profiles', 'designation')
    op.drop_column('artisan_profiles', 'company_size')
    op.drop_column('artisan_profiles', 'website')
    op.drop_column('artisan_profiles', 'registration_number')
    op.drop_column('artisan_profiles', 'established_year')
    op.drop_column('artisan_profiles', 'products_services_offered')
    op.drop_column('artisan_profiles', 'gst_number')
    op.drop_column('artisan_profiles', 'target_markets')
    op.drop_column('artisan_profiles', 'contact_person_name')
    op.drop_column('artisan_profiles', 'annual_turnover')
    op.add_column('products', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('diameter', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('dimension_unit', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'dimension_unit')
    op.drop_column('products', 'diameter')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    op.add_column('artisan_profiles', sa.Column('annual_turnover', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('contact_person_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('target_markets', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('gst_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('products_services_offered', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('established_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('company_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artisan_profiles', sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
